#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__
#define DISPLAY_STARTUPSCENE_TIME 2.0f
#define TRANSITION_TIME 0.8f
#define AIRPLANE_SPAWN_FREQUENCY 0.005
#define LOWER_SCREEN_PIPE_THRESHOLD 0.6
#define UPPER_SCREEN_PIPE_THRESHOLD 0.95
#define PIPE_GAP 190
#define PIPE_MOVEMENT_DURATION 0.03

#define PIPE_SPAWN_FREQUENCY 0.00002


#define HILL_MOVEMENT_DURATION 0.05
#define HILL_SPAWN_FREQUENCY 0.02

#define AIRPLANE_COLLISION_BITMASK 0x000001
#define HILL_COLLISION_BITMASK 0x000002

#define APPLE_COLLISION_BITMASK 0x000003

#define APPLE_SPAWN_FREQUENCY 0.01
#define LOWER_APPLE_THRESHOLD 0.1
#define UPPER_APPLE_THRESHOLD 0.65

#define LOWER_CURVE_THRESHOLD 0.35
#define UPPER_CURVE_THRESHOLD 0.85
#define CURVE_GAP_LIMIT 80
#define CURVE_MOVEMENT_SPEED 0.01
#define CURVE_MOVEMENT_DURATION 0.05
#define CURVE_SPAWN_FREQUENCY 0.02

#define SCORE_FONT_SIZE 0.1

#define TUNNEL_MOVEMENT_DURATION 0.08

#define ACTION_X_OFFSET 2000

#endif // __DEFINITIONS_H__
